# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4345d4b14e5b28047aa3d332356cb34e5a5919e6790ed7fec58f14bb7aa5e8ebae69d519fbfa214ee417253d528389d5607453ad01c8809c83f72c5008aaa394

test:
  secret_key_base: c42def050e723a5d32dcb8f4d609977dcc7aada9143bf983a83dc0dc7a73bbe299c5ccbf737ed7650e0ca6649f97122479417524f638c88fe42e65d91e065f62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
